networks:
  homelab_network:
    name: homelab_network
    external: true

services:
  nexus:
    image: sonatype/nexus3:3.82.0
    volumes:
      - nexus_data:/nexus-data
    networks:
      - homelab_network

volumes:
  nexus_data:
    driver: local