networks:
  homelab_network:
    name: homelab_network
    external: true

services:
  sonarqube_postgresql:
    image: docker.io/bitnami/postgresql:17.5.0
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=sonarqube
      - POSTGRESQL_PASSWORD=Q9Cjts96us87hVw1PC8dEWZuj
      - POSTGRESQL_DATABASE=sonarqube
  sonarqube:
    image: docker.io/bitnami/sonarqube:25.7.0
    volumes:
      - 'sonarqube_data:/bitnami/sonarqube'
    depends_on:
      - sonarqube_postgresql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - SONARQUBE_DATABASE_HOST=sonarqube_postgresql
      - SONARQUBE_DATABASE_PORT_NUMBER=5432
      - SONARQUBE_DATABASE_USER=sonarqube
      - SONARQUBE_DATABASE_PASSWORD=Q9Cjts96us87hVw1PC8dEWZuj
      - SONARQUBE_DATABASE_NAME=sonarqube
volumes:
  postgresql_data:
    driver: local
  sonarqube_data:
    driver: local