FROM 852869911313.dkr.ecr.ap-south-1.amazonaws.com/azure_devops_agent:base-3.218.0

RUN DEBIAN_FRONTEND=noninteractive apt-get update

RUN DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends \
  docker.io