networks:
  homelab_network:
    name: homelab_network
    external: true

services:
  # kc_postgres:
  #   image: postgres:17.5
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: keycloak
  #     POSTGRES_USER: keycloak
  #     POSTGRES_PASSWORD: o22Cve0sIurpZvdP3u2SC0wjVflITf
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -U keycloak -d keycloak"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #   networks:
  #     - homelab_network

  keycloak_postgresql:
    image: docker.io/bitnami/postgresql:17.5.0
    restart: unless-stopped
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=keycloak
      - POSTGRESQL_PASSWORD=o22Cve0sIurpZvdP3u2SC0wjVflITf
      - POSTGRESQL_DATABASE=keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - homelab_network
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    restart: unless-stopped
    depends_on:
      - keycloak_postgresql
    environment:
      # Bootstrap admin (first run only)
      KC_BOOTSTRAP_ADMIN_USERNAME: shoaib
      KC_BOOTSTRAP_ADMIN_PASSWORD: Shoaib@123

      # Database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_postgresql:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: o22Cve0sIurpZvdP3u2SC0wjVflITf

      # Hostname v2 (USE THESE — drop the *URL/*ADMIN_URL v1 vars)
      KC_HOSTNAME: https://keycloak.deploywizard.in
      KC_HOSTNAME_ADMIN: https://keycloak.deploywizard.in
      KC_HOSTNAME_STRICT: "true"

      # Reverse proxy config (required!)
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
    command: ["start"]
    networks:
      - homelab_network

volumes:
  postgresql_data:
    driver: local