version: '3.3'

services:
  rocketchat:
    image: rocket.chat:${RELEASE:-latest}
    restart: on-failure
    environment:
      # - MONGO_URL=${MONGO_URL:-mongodb://${MONGODB_USERNAME:-shoaib}:${MONGODB_PASSWORD:-Shoaib123}@mongodb:27017/${MONGODB_DATABASE:-rocketchat}}
      - MONGO_URL=mongodb://shoaib:Shoaib123@mongodb:27017/rocketchat
      # - MONGO_OPLOG_URL="${MONGO_OPLOG_URL:-mongdb://${MONGODB_USERNAME:-shoaib}:${MONGODB_PASSWORD:-Shoaib123}@mongodb:27017/local}"
      - MONGO_OPLOG_URL=mongodb://shoaib:Shoaib123@mongodb:27017/local
      - ROOT_URL=${ROOT_URL:-http://localhost:3000}
      - PORT=${PORT:-3000}
      - DEPLOY_METHOD=docker
    depends_on:
      - mongodb
    expose:
      - ${PORT:-3000}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
  mongodb:
    image: bitnami/mongodb:${MONGO_VERSION:-6.0}
    restart: on-failure
    environment:
      - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD:-Root123}
      - MONGODB_USERNAME=${MONGODB_USERNAME:-shoaib}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD:-Shoaib123}
      - MONGODB_DATABASE=${MONGODB_DATABASE:-rocketchat}
    volumes:
      - mongo_data:/bitnami/mongodb
  
volumes:
  mongo_data:
    driver: local