networks:
  homelab_network:
    name: homelab_network
    external: true

services:
  portainer:
    image: portainer/portainer-ce:2.32.0-alpine
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.yourdomain.com
    volumes:
      - 'portainer_data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - homelab_network
volumes:
  portainer_data:
    driver: local