networks:
  homelab_network:
    name: homelab_network
    external: true

services:
  jenkins:
    # image: jenkins/jenkins:2.521-jdk21
    environment:
      - PLUGINS_FORCE_UPGRADE=true
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs/jenkins.yaml
      - OIDC_CLIENT_SECRET=OGIlxuZZkRhagiGytCCHvMXfwTnHT9iW
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
    # restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    # ports:
    #   - '8080:8080'
    #   - '50000:50000'
    networks:
      - homelab_network
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - ./jenkins.yaml:/var/jenkins_home/casc_configs/jenkins.yaml
      # - '/var/run/docker.sock:/var/run/docker.sock'
    # group_add:
    #   - '997'
    
volumes:
  jenkins_home:
    driver: local