server {
  listen 443 ssl;
  server_name airflow.hadiya.local;
  access_log  /var/log/nginx/airflow-access.log main;
  error_log /var/log/nginx/airflow-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_airflow airflow_web;
    proxy_pass http://$upstream_airflow:8080;
    proxy_buffering off;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
