server {
  listen 443 ssl;
  server_name rabbitmq.hadiya.local;
  access_log  /var/log/nginx/rabbitmq-access.log main;
  error_log /var/log/nginx/rabbitmq-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_rabbitmq rabbitmq;
    proxy_pass http://$upstream_rabbitmq:15672;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
