server {
  listen 443 ssl;
  server_name sonarqube.hadiya.local;
  access_log  /var/log/nginx/sonarqube-access.log main;
  error_log /var/log/nginx/sonarqube-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_sonarqube sonarqube;
    proxy_pass http://$upstream_sonarqube:9000;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
