version: '3.9'

services:
  jenkins:
    image: docker.io/shoaib1999/jenkins-docker:lts-jdk11
    ports:
      - '8090:8080'
      - '50000:50000'
    volumes:
      - 'jenkins_home:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'
    group_add:
      - '997'
    
volumes:
  jenkins_home:
    driver: local