# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket       = "all-project-tfstates-07062025"
    encrypt      = true
    key          = "nonprod/vpc/terraform.tfstate"
    region       = "ap-south-1"
    use_lockfile = true
  }
}
