server {
  listen 443 ssl;
  server_name grafana.hadiya.local;
  access_log  /var/log/nginx/grafana-access.log main;
  error_log /var/log/nginx/grafana-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_grafana grafana;
    proxy_pass http://$upstream_grafana:3000;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $http_host;
  }
}
