server {
    listen 443 ssl;
    server_name homelab.deploywizard.in www.deploywizard.in homelab.deploywizard.local www.deploywizard.local;
    access_log  /var/log/nginx/landing-access.log main;
    error_log /var/log/nginx/landing-error.log error;
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}