server {
  listen 443 ssl;
  server_name nexus.hadiya.local;
  access_log  /var/log/nginx/nexus-access.log main;
  error_log /var/log/nginx/nexus-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_nexus nexus;
    proxy_pass http://$upstream_nexus:8081;
    proxy_buffering off;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Host $host;
  }
}
server {
  resolver 127.0.0.11 valid=30s;
  listen 443 ssl;
  server_name hcr-proxy.hadiya.local;
  location / {
    set $upstream_nexus nexus;
    proxy_pass http://$upstream_nexus:5555;
    proxy_buffering off;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
server {
  listen 443 ssl;
  server_name hcr-hosted.hadiya.local;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_nexus nexus;
    proxy_pass http://$upstream_nexus:6666;
    proxy_buffering off;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
server {
  listen 443 ssl;
  server_name hcr.hadiya.local;
  access_log  /var/log/nginx/hcr-access.log main;
  error_log /var/log/nginx/hcr-error.log error;
  location / {
    resolver 127.0.0.11 valid=30s;
    set $upstream_nexus nexus;
    proxy_pass http://$upstream_nexus:7777;
    proxy_buffering off;
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}