version: '3'

services:
  keycloak:
    image: shoaib1999/keycloak:latest
    # command: ["start"]
    environment:
      - KC_DB_URL=jdbc:mysql://mysql:3306/keycloak
      - KC_DB_USERNAME=shoaib
      - KC_DB_PASSWORD=Shoaib123
      - KC_HOSTNAME=keycloak.hadiya.ml
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=Admin@123
    ports:
      - 443:8443
    networks:
      - keycloak_net
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=shoaib
      - MYSQL_PASSWORD=Shoaib123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - keycloak_net
volumes:
  mysql_data:
    driver: local

networks:
  keycloak_net:
    driver: bridge