name: Nonprod - persistent provisioner

on:
  workflow_dispatch:

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest
    environment: DEV
    permissions:
      actions: read
      contents: read
      security-events: write
    env:
      TF_WORKDIR: ./infra/envs/nonprod/persistent
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@v0.1.0
        with:
          working_directory: ${{ env.TF_WORKDIR }}
          full_repo_scan: true
          sarif_file: tfsec-results.sarif

      # - name: tfsec
      #   uses: aquasecurity/tfsec-action@v1.0.3
      #   with:
      #     soft_fail: true
      #     format: sarif
      #     github_token: ${{ github.token }}
      #     working_directory: ${{ env.TF_WORKDIR }}
      #     additional_args: --force-all-dirs --out tfsec-results.sarif

      - name: Upload SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: tfsec-results.sarif