name: homelab-teardown
on:
  workflow_dispatch:
    inputs:
      make_ami:
        type: boolean
        description: Create AMI
        default: true
      # snapshot_data_volume:
      #   type: boolean
      #   description: Snapshot Data Volume
      #   default: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: DEV
    env:
      AWS_REGION: ap-south-1
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Output values
        id: tfout
        working-directory: terraform
        run: |
          terraform output -json > outputs.json
          echo "INSTANCE_ID=$(jq -r .instance_id.value outputs.json)" >> $GITHUB_ENV
          # echo "DATA_VOL_ID=$(jq -r .data_volume_id.value outputs.json)" >> $GITHUB_ENV

      - name: Create AMI
        if: ${{ github.event.inputs.make_ami == 'true' }}
        run: |
          AMI_ID=$(aws ec2 create-image \
            --instance-id "$INSTANCE_ID" \
            --name "homelab-ami-$(date +%Y%m%d%H%M%S)" \
            --no-reboot \
            --query 'ImageId' --output text)
          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
          echo $AMI_ID > ami_id.txt

      # - name: Snapshot data volume
      #   if: ${{ github.event.inputs.snapshot_data_volume == 'true' && env.DATA_VOL_ID != 'null' }}
      #   run: |
      #     SNAP_ID=$(aws ec2 create-snapshot \
      #       --volume-id "$DATA_VOL_ID" \
      #       --description "homelab-data-$(date +%Y%m%d%H%M%S)" \
      #       --query 'SnapshotId' --output text)
      #     echo "SNAPSHOT_ID=$SNAP_ID" >> $GITHUB_ENV
      #     echo $SNAP_ID > snapshot_id.txt

      - name: Upload artifact (ids)
        uses: actions/upload-artifact@v4
        with:
          name: restore-ids
          path: |
            ami_id.txt
            # snapshot_id.txt

      # - name: Terraform Destroy
      #   working-directory: terraform
      #   run: terraform destroy -auto-approve
