name: Decommision Homelab EKS

on:
  workflow_dispatch:
  push:
    branches:
      - feature/provision-github-action

jobs:
  infrastructure:
    name: Decommission
    runs-on: ubuntu-latest
    environment: DEV

    env:
      AWS_REGION: ap-south-1
      TG_WORKDIR: ./infra/envs/nonprod   # adjust to your terragrunt.hcl path

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Install Terragrunt
        run: |
          curl -Lo /usr/local/bin/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.66.4/terragrunt_linux_amd64
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: Terragrunt Init - EKS
        run: terragrunt init --terragrunt-disable-bucket-update
        working-directory: ${{ env.TG_WORKDIR }}/eks

      - name: Terragrunt Destroy - EKS
        run: terragrunt destroy -auto-approve
        working-directory: ${{ env.TG_WORKDIR }}/eks

      - name: Terragrunt Init - VPC
        run: terragrunt init --terragrunt-disable-bucket-update
        working-directory: ${{ env.TG_WORKDIR }}/vpc

      - name: Terragrunt Destroy - VPC
        run: terragrunt destroy -auto-approve
        working-directory: ${{ env.TG_WORKDIR }}/vpc